version: '3'

services:

  database:
    container_name: database
    image: mysql:8.0.12
    networks:
      - garage_app
    ports:
      - "33064:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: gdb
    volumes:
        - garage-app-database:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - garage_app
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password

  nginx:
    container_name: nginx
    build: 
      context: ./docker
    networks:
      - garage_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/web

  php:
    container_name: php
    build:
      context: ./docker/php
    networks:
      - garage_app
    volumes:
      - .:/var/www/web

networks:
  garage_app:
    name: garage_app

volumes:
  garage-app-database:
    driver: local