version: '3'

services:

  database:
    container_name: database
    # image: mysql:8.0.12
    # image: mysql:5.7.12
    image: mariadb:latest
    networks:
      - garage_app
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: gdb
    volumes:
        - garage-app-database:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - garage_app
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password

  # nginx:
  #   container_name: nginx
  #   build: 
  #     context: ./docker
  #   networks:
  #     - garage_app
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - .:/var/www/web

  app:
    container_name: app
    build:
      context: .
    # networks:
    #   - garage_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

networks:
  garage_app:
    name: garage_app

volumes:
  garage-app-database:
    driver: local