version: '3'

services:

  database:
    container_name: database
    image: mariadb:latest
    networks:
      - garage_app
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
    volumes:
        - garage-app-database:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - garage_app
    ports:
      - "${PHPMYADMIN_EXTERNAL_PORT}:${PHPMYADMIN_PORT}"
    depends_on:
      - database
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}

  app:
    container_name: app
    build:
      context: .
    networks:
      - garage_app
    ports:
      - "${APP_EXTERNAL_PORT}:${APP_PORT}"
    environment:
      HOST: ${DB_HOST}
      PORT: ${DB_PORT}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}
      DATABASE: ${DB_NAME}
    volumes:
      - .:/var/www/html

networks:
  garage_app:
    name: garage_app

volumes:
  garage-app-database:
    driver: local